 task :delete_fantom_users => :environment do
 fantoms = [      
    :email => 'uayaku_3337@hotmail.com',
    :email => 'angelik_12@yahoo.com.mx',
    :email => 'dra.sofiaarce@gmail.com',
    :email => 'b_kau5@hotmail.com',
    :email => 'drjuancardenas82@gmail.com',
    :email => 'cgdh333@hotmail.com',
    :email => 'gaby.cortes.meda@gmail.com',
    :email => 'tufibi@hotmail.com',
    :email => 'jakanywong@hotmail.com',
    :email => 'drp.hepb@gmail.com',
    :email => 'lilys111@hotmail.com',
    :email => 'nglzr@hotmail.com',
    :email => 'noveloadrian@hotmail.com',
    :email => 'paola_agg@hotmail.com',
    :email => 'seyegn@hotmail.com',
    :email => 'sky_palace@hotmail.com',
    :email => 'g_teran@hotmail.com',
    :email => 'viopsiq@hotmail.com',
    :email => 'abrakadabrados@hotmail.com',
    :email => 'draxeniaduran@gmail.com',
    :email => 'azul3112@yahoo.com',
    :email => 'jbarahona83@yahoo.com',
    :email => 'monyk_81sp@hotmail.com',
    :email => 'josefa_cavazos@hotmail.com',
    :email => 'tizsauer@hotmail.com',
    :email => 'nestor_391@hotmail.com',
    :email => 'iggallo@prodigy.net.mx',
    :email => 'igmar1978@hotmail.com',
    :email => 'dr_hulk@hotmail.com',
    :email => 'emmanuelsarmientoh@hotmail.com',
    :email => 'diazdominguezd@yahoo.com',
    :email => 'hector5808@prodigy.net.mx',
    :email => 'marielacalzado@yahoo.com.mx',
    :email => 'jahdaw@yahoo.com',
    :email => 'migueslun@hotmail.com',
    :email => 'dranogales@hotmail.com',
    :email => 'galygalatsi76@hotmail.com',
    :email => 'nagondel@yahoo.com',
    :email => 'laurabanic@hotmail.com',
    :email => 'daliabecerra@hotmail.com',
    :email => 'anateresadc@yahoo.com',
    :email => 'dra_delarosam@hotmail.com',
    :email => 'yarieladg@hotmail.com',
    :email => 'cavazosolivo@yahoo.com',
    :email => 'psiquiatrasvip@gmail.com',
    :email => 'nayepam@yahoo.com.mx',
    :email => 'carzet@msn.com',
    :email => 'julissa.areli.palomino@hotmail.com',
    :email => 'geovanni.ortiz@hotmail.com',
    :email => 'alberto.diaz.gonzalez@gmail.com',
    :email => 'aldamakarla@gmail.com',
    :email => 'silverio.rdz@hotmail.com',
    :email => 'ayodele123_4@hotmail.com',
    :email => 'armandorico30@hotmail.com',
    :email => 'mario__co@hotmail.com',
    :email => 'angelbp88@hotmail.com',
    :email => 'carlos_javier_jjr@hotmail.com',
    :email => 'periliz@hotmail.com',
    :email => 'bri266@hotmail.com',
    :email => 'funny_greenboy@hotmail.com',
    :email => 'chaltecali@hotmail.com',
    :email => 'guszoo5366@gmail.com',
    :email => 'beliar_alejandro@hotmail.com',
    :email => 'ed_alhe190@hotmail.com',
    :email => 'yowalatzin@gmail.com',
    :email => 'elgranzeus90@hotmail.com',
    :email => 'aperezarzt@gmail.com',
    :email => 'tanque_master@hotmail.com',
    :email => 'beeverynice@hotmail.com',
    :email => 'armando_rivera_uam@hotmail.com',
    :email => 'vanghel@hotmail.com',
    :email => 'hao1000@hotmail.com',
    :email => 'bertha_hernandez_2855@hotmail.com',
    :email => 'mochabatx@hotmail.com',
    :email => 'mariocoor@gmail.com',
    :email => 'tania_acevedo89@hotmail.com',
    :email => 'meaq13@hotmail.com',
    :email => 'almaguer_989@hotmail.com',
    :email => 'leonardodcm@gmail.com',
    :email => 'lizanderri@yahoo.com.mx',
    :email => 'danielfb1706@gmail.com',
    :email => 'vicfrutis@yahoo.com.mx',
    :email => 'choche_lui13@hotmail.com',
    :email => 'sakura_trc_ccs@hotmail.com',
    :email => 'cesarjara9@yahoo.com.mx',
    :email => 'bamad90f@gmail.com',
    :email => 'drmartinezes@hotmail.com',
    :email => 'fxdkraken@hotmail.com',
    :email => 'ponchoxbox1990@hotmail.com',
    :email => 'limg_15@hotmail.com',
    :email => 'shakaexit_25@hotmail.com',
    :email => 'adrimirez5@hotmail.com',
    :email => 'rimbaud1918@gmail.com',
    :email => 'airamsalas27@gmail.com',
    :email => 'wop23_phakoopz@hotmail.com',
    :email => 'chivantonio_zapo@hotmail.com',
    :email => 'laou_nova@hotmail.com',
    :email => 'drjacs@gmail.com',
    :email => 'sakura_li1516@hotmail.com',
    :email => 'sakuyahwu@gmail.com',
    :email => 'jpaviac1@hotmail.com'
   ]

  fantoms = [      
    'uayaku_3337@hotmail.com',
    'angelik_12@yahoo.com.mx',
    'dra.sofiaarce@gmail.com',
    'b_kau5@hotmail.com',
    'drjuancardenas82@gmail.com',
    'cgdh333@hotmail.com',
    'gaby.cortes.meda@gmail.com',
    'tufibi@hotmail.com',
    'jakanywong@hotmail.com',
    'drp.hepb@gmail.com',
    'lilys111@hotmail.com',
    'nglzr@hotmail.com',
    'noveloadrian@hotmail.com',
    'paola_agg@hotmail.com',
    'seyegn@hotmail.com',
    'sky_palace@hotmail.com',
    'g_teran@hotmail.com',
    'viopsiq@hotmail.com',
    'abrakadabrados@hotmail.com',
    'draxeniaduran@gmail.com',
    'azul3112@yahoo.com',
    'jbarahona83@yahoo.com',
    'monyk_81sp@hotmail.com',
    'josefa_cavazos@hotmail.com',
    'tizsauer@hotmail.com',
    'nestor_391@hotmail.com',
    'iggallo@prodigy.net.mx',
    'igmar1978@hotmail.com',
    'dr_hulk@hotmail.com',
    'emmanuelsarmientoh@hotmail.com',
    'diazdominguezd@yahoo.com',
    'hector5808@prodigy.net.mx',
    'marielacalzado@yahoo.com.mx',
    'jahdaw@yahoo.com',
    'migueslun@hotmail.com',
    'dranogales@hotmail.com',
    'galygalatsi76@hotmail.com',
    'nagondel@yahoo.com',
    'laurabanic@hotmail.com',
    'daliabecerra@hotmail.com',
    'anateresadc@yahoo.com',
    'dra_delarosam@hotmail.com',
    'yarieladg@hotmail.com',
    'cavazosolivo@yahoo.com',
    'psiquiatrasvip@gmail.com',
    'nayepam@yahoo.com.mx',
    'carzet@msn.com',
    'julissa.areli.palomino@hotmail.com',
    'geovanni.ortiz@hotmail.com',
    'alberto.diaz.gonzalez@gmail.com',
    'aldamakarla@gmail.com',
    'silverio.rdz@hotmail.com',
    'ayodele123_4@hotmail.com',
    'armandorico30@hotmail.com',
    'mario__co@hotmail.com',
    'angelbp88@hotmail.com',
    'carlos_javier_jjr@hotmail.com',
    'periliz@hotmail.com',
    'bri266@hotmail.com',
    'funny_greenboy@hotmail.com',
    'chaltecali@hotmail.com',
    'guszoo5366@gmail.com',
    'beliar_alejandro@hotmail.com',
    'ed_alhe190@hotmail.com',
    'yowalatzin@gmail.com',
    'elgranzeus90@hotmail.com',
    'aperezarzt@gmail.com',
    'tanque_master@hotmail.com',
    'beeverynice@hotmail.com',
    'armando_rivera_uam@hotmail.com',
    'vanghel@hotmail.com',
    'hao1000@hotmail.com',
    'bertha_hernandez_2855@hotmail.com',
    'mochabatx@hotmail.com',
    'mariocoor@gmail.com',
    'tania_acevedo89@hotmail.com',
    'meaq13@hotmail.com',
    'almaguer_989@hotmail.com',
    'leonardodcm@gmail.com',
    'lizanderri@yahoo.com.mx',
    'danielfb1706@gmail.com',
    'vicfrutis@yahoo.com.mx',
    'choche_lui13@hotmail.com',
    'sakura_trc_ccs@hotmail.com',
    'cesarjara9@yahoo.com.mx',
    'bamad90f@gmail.com',
    'drmartinezes@hotmail.com',
    'fxdkraken@hotmail.com',
    'ponchoxbox1990@hotmail.com',
    'limg_15@hotmail.com',
    'shakaexit_25@hotmail.com',
    'adrimirez5@hotmail.com',
    'rimbaud1918@gmail.com',
    'airamsalas27@gmail.com',
    'wop23_phakoopz@hotmail.com',
    'chivantonio_zapo@hotmail.com',
    'laou_nova@hotmail.com',
    'drjacs@gmail.com',
    'sakura_li1516@hotmail.com',
    'sakuyahwu@gmail.com',
    'jpaviac1@hotmail.com'
   ]
   puts fantoms.count
    #network_id
    # network_id = 6
    #dar de alta usuarios 3b
    users = User.where(:email => fantoms)

    puts users.count
    users.delete_all
    puts users.count
end