source 'https://rubygems.org'

gem 'rails', '3.2.19'
gem 'pg', groups: [:production]
gem 'devise', '2.2.8'
gem 'json'
gem 'charlock_holmes'
gem 'watu_table_builder', require: 'table_builder'
gem 'carrierwave', require: ['carrierwave', 'carrierwave/processing/mime_types']
gem 'fog'
gem 'mime-types'
gem 'mini_magick'
gem 'geocoder'
gem 'useragent'
gem 'omniauth'
gem 'google-api-client', require: 'google/api_client'
gem 'omniauth-google-oauth2'
gem 'omniauth-facebook'
gem 'haml-rails', '~> 0.4.0'
gem 'jquery-rails'
gem 'acts_as_commentable'
gem 'acts_as_votable', '~> 0.5.0'
gem 'auto_html'
gem 'will_paginate', '3.0.3'
gem 'state_machine'
gem 'thin'
gem 'private_pub', git: 'git://github.com/ryanb/private_pub.git'
gem 'declarative_authorization'
gem 'jquery-fileupload-rails'
gem 'bcrypt-ruby', '~> 3.0.0'
gem 'nifty-generators', group: :development
gem 'jbuilder'
gem 'httparty'
gem 'pdfkit'
gem 'launchy', '~>2.1.2'
gem 'active_attr'
gem 'dropbox-sdk', '~> 1.5.1'
gem 'mediawiki-gateway'
gem 'omniauth-dropbox'
gem 'dropbox-api'
gem 'delayed_job_active_record'
gem 'daemons'
gem 'aws-ses', '~> 0.5.0', require: 'aws/ses'
gem 'exception_notification', '~> 3.0.1' 
gem 'activeadmin'
gem 'meta_search', '>= 1.1.0.pre'
gem 'wuparty', '~> 1.2.6'
gem 'meta-tags'
gem 'sidekiq', '~> 3.1.2'
gem 'mixpanel-ruby'
gem 'ruby_parser'
gem 'rails_config'
gem 'multi_logger'

group :assets do
  gem 'sass', '3.2.13'
  gem 'sass-rails', '~> 3.2.3'
  gem 'bourbon', '~> 3.2.3'
  gem 'handlebars_assets'
  gem 'coffee-script'
  gem 'uglifier', '>= 1.0.3'
end

group :development do
  gem 'binding_of_caller'
  gem 'meta_request'
  gem 'rails_best_practices'
  gem 'unicorn'
  gem 'sqlite3'
  gem 'rubocop'
end

group :test do
  gem 'cucumber-rails', require: false
  gem 'factory_girl_rails'
  gem 'database_cleaner'
  gem 'rspec-sidekiq'
  gem 'rspec-expectations'
  gem 'rspec-rails', '~> 3.0'
  gem 'capybara'
  gem 'selenium-webdriver', '~> 2.44.0'
  gem 'capybara-webkit'
end
