
# WUFOO forms
ACCOUNT = 'cursame'
API_KEY = 'F0GC-XKMU-SADX-HJ8Z'

# Bit
BIT_API_KEY = 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJCSVQgQWNhZGVtaWMgTWFuYWdlcq4iLCJhdWQiOiJodHRwOi8vd3d3LmFjYWRlbWljbWFuYWdlci5teCIsImlhdCI6MTQyNDQ3NjMxMCwiZXhwIjoiMTc0MDA5NTUxMCIsImVzY3VlbGEiOiJlbGVtZW50YXJ5IiwidG9rZW4iOiI5NGRhMjczMS0wOGY3LTQ5N2YtOTQ4ZC1kZmY3MGU5ZDYxOTkifQ.tU0qNWf1-abA6_mBdNYxhSOt4xxvj0-4Z23fvq8hZQGHoNjJIZ3XZt21a--nuBix6TCujjRSYL5Vm-BwMWktiw'

# Cards per page in lists
CARDS_PER_PAGE = 10
COURSES_PER_PAGE = 9
COMMENTS_PER_PAGE = 3
POST_PER_PAGE = 15
MANAGERS_RECORDS_PER_PAGE = 25