
# WUFOO forms
ACCOUNT = 'cursame'
API_KEY = 'F0GC-XKMU-SADX-HJ8Z'

# Cards per page in lists
CARDS_PER_PAGE = 10
COURSES_PER_PAGE = 9
COMMENTS_PER_PAGE = 3
POST_PER_PAGE = 15
MANAGERS_RECORDS_PER_PAGE = 25