default: &defaults
  # Your push api key, it is possible to set this dynamically using ERB:
  # push_api_key: "<%= ENV['APPSIGNAL_PUSH_API_KEY'] %>"
  push_api_key: "141eeba9-1b01-443c-b492-0ed81b118eb6"

  # Your app's name
  name: "Cursame30Lb"

  # The cuttoff point in ms above which a request is considered slow, default is 200
  # slow_request_threshold: 200

# Configuration per environment, leave out an environment or set active
# to false to not push metrics for that environment.
cursame-test:
  <<: *defaults
  active: true

development:
  <<: *defaults
  active: true

emprendedores:
  <<: *defaults
  active: true

production:
  <<: *defaults
  active: true

subtest:
  <<: *defaults
  active: true
