development:
  adapter: postgresql
  database: cursame_development
  encoding: utf8
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: cursame_test
  encoding: utf8
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  pool: 10
  database: <%= ENV['CURSAME_DATABASE_NAME'] %>
  username: <%= ENV['CURSAME_DATABASE_USERNAME'] %>
  password: <%= ENV['CURSAME_DATABASE_PASSWORD'] %>
  host: <%= ENV['CURSAME_DATABASE_HOST'] %>
