mixpanel:
  token: 16de115771d44b05c5773929359c59a6
gospel:
  token: 938592hhhf4hui23ui2bfbu5i5y
  host: cursame-gospel.herokuapp.com
  port: 80
  path:
    create_user: /create_user
    create_network: /create_network
    register_session: /register_session
bit:
  host: api.academic.mx
  port: 80
  path:
    groups: /v1/grupos
    group_students: /v1/alumnos
    group_teachers: /v1/profesores
    group_evaluations: /v1/evaluaciones
    evaluation: /v1/escalaRubrica
    activity: /v1/actividadesRubrica
    grade: /v1/calificacionesRubrica
